import { replaceManagedRegion } from '../../domain/services/ManagedRegion';
import { WikiRepositoryPort } from '../ports/WikiRepositoryPort';

export interface Gap {
  /** Driver basename (no `.md`). */
  driver: string;
  /** Why it is uncovered (deterministic lint message). */
  reason: string;
}

export interface UpdateGapAnalysisInput {
  /** Open gaps, typically mapped from uncovered-driver lint findings. */
  gaps: Gap[];
}

export interface UpdateGapAnalysisDeps {
  repo: WikiRepositoryPort;
}

export interface UpdateGapAnalysisResult {
  path: string;
  created: boolean;
  gapCount: number;
}

const FILE = 'gap-analysis.md';
const START = '<!-- arch-wiki:gaps:start -->';
const END = '<!-- arch-wiki:gaps:end -->';
const SCAFFOLD =
  '---\ntype: gap-analysis\ntags: [gap-analysis]\n---\n\n' +
  '# Gap Analysis\n\n' +
  'Open gaps below are regenerated by `arch-wiki update-gap-analysis` between the\n' +
  'markers. Notes outside the managed region are preserved.\n\n';

/**
 * Regenerate the managed "open gaps" region of `gap-analysis.md` from the current
 * uncovered-driver gaps. This is the OUTPUT of lint and the INPUT of the driver-gap
 * questionnaire (closes the §6.2 loop). Its own use-case (not the keyed-row helper,
 * fix #11): empty gaps ⇒ empty region (never deletes the file); human notes outside
 * the markers survive. Deterministic.
 */
export async function updateGapAnalysis(
  input: UpdateGapAnalysisInput,
  deps: UpdateGapAnalysisDeps,
): Promise<UpdateGapAnalysisResult> {
  const { repo } = deps;
  const sorted = [...input.gaps].sort((a, b) => a.driver.localeCompare(b.driver));
  const body = sorted.map((g) => `- [[${g.driver}]] — ${g.reason}`).join('\n');

  const exists = await repo.exists(FILE);
  const content = exists ? await repo.read(FILE) : null;
  const next = replaceManagedRegion(content, START, END, body, SCAFFOLD);
  await repo.write(FILE, next);
  return { path: FILE, created: !exists, gapCount: sorted.length };
}
